### ISSUE TITLE
Booking on Behalf of

### ISSUE THREAD

**Issue by SamuelJHolmes** [ValuationOffice/VORBS#56] opened 2018-03-28 13:35 UTC
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1.As admin use the on behalf of box when booking 
2.
3.

What happens?
-------------
-> Booking is made in admins name
-> Admin receives email nothing is sent to the on behalf user    

What were you expecting to happen?
----------------------------------
->The on behalf of user should receive confirmation email and the booking should be in their "My Bookings".

Any logs, error output, etc? 
----------------------------
(You can set the loglevel to 'Trace' in the web.config to produce a more detailed log output)

(If it’s long, please paste to https://pastebin.com/ and insert the link here.)

->

Any other comments?
-------------------
->

What versions of software are you using?
----------------------------------------
**Operating System:**

**Software Version:**

**Browser name and version used:**

**Comment by LynchyC** [comment] 2018-03-29 06:54
Closed issue as it is a duplicate of #41

**Closed** 2018-03-29 06:54 UTC
